### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by bpsizemore** [Gnovel/Srcalyzer#17]
A page that will allow a user to register. It needs to have all necessary fields. Each user that wishes to register will need a registration code, that can be set by the administrator.

**Comment by amart97** [comment]
Is this an account registration page or a class registration page? I see the benefits of having both put together when making an account, but what if I have an account and want to just register for a new class?

**Comment by bpsizemore** [comment]
An account registration page. IMO class registration should be separate. You might need to register for multiple classes or you might be able to register for a server before you register for a class.

**Comment by amart97** [comment]
I’m not sure how to update an issue on what needs to be done going forward from here, so I’ll just make a comment on this thread.

- “More Pretty”
- Determine what items in form need removed or if any need added
- Determine viability of layout (fix form positioning)
