### ISSUE TITLE
Course Creation Page

### ISSUE THREAD

**Issue by bpsizemore** [Gnovel/Srcalyzer#18]
Create a page to allow an educator to create a new course.

**Comment by amart97** [comment]
Here’s a design for creating a new course.  Again ignoring the color scheme until we decide upon one.  As far as the registration end date goes, I just grabbed a generic one from online.  They don’t seem too hard to implement.

[CourseRegistrationDesign.pptx](https://github.com/Gnovel/Srcalyzer/files/352260/CourseRegistrationDesign.pptx)

**Comment by amart97** [comment]
Update: Need to actually create the course table in Mongo and check if a user has permission to actually create a course.  Need to make it pretty.
